--- 
class_name: 
slug: training_personnel
updated_by_id: 
sitemap: true
layout_name: <inherit> [default_title_left]
change_frequency: weekly
title: !binary |
  5Lq65omN5Z+55YW7

virtual: false
created_by_id: 1
priority: "0.5"
breadcrumb: !binary |
  5Lq65omN5Z+55YW7

enable_comments: false
comments_count: 0
description: 
published_at: 
status_id: 100
keywords: 
