--- 
class_name: ""
slug: training_personnel
updated_by_id: 
layout_name: !binary |
  PGluaGVyaXQ+IFvpu5jorqTluIPlsYBd

title: !binary |
  5Lq65omN5Z+55YW7

virtual: false
created_by_id: 1
breadcrumb: !binary |
  5Lq65omN5Z+55YW7

description: ""
published_at: 
status_id: 1
keywords: ""
